sql_files:
  - file: sql/01_catchment_current.sql
  - file: sql/02_catchment_planned.sql
  - file: sql/03_catchment_area_totals.sql
  - file: sql/04_cover.sql
  - file: sql/05_reach.sql
  - file: sql/06_wastewater_structure.sql
